In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])
print(arr,arr.shape)
print(arr,arr.dtype)


arr2 = np.array([1,2,3,4,5,"Dibya"])
print(arr2,arr2.shape)
print(arr2,arr2.dtype)


arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D,arr2D.shape)
print(arr2D,arr2D.dtype)
# arr2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12,13]]) this is not possible to create


[1 2 3 4 5] (5,)
[1 2 3 4 5] int64
['1' '2' '3' '4' '5' 'Dibya'] (6,)
['1' '2' '3' '4' '5' 'Dibya'] <U21
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] int64
