In [3]:
import numpy as np

In [5]:
arr1=np.zeros((2,3),dtype="int64")
print(arr1,arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [7]:
arr2=np.ones((2))
print(arr2,arr2.shape)

[1. 1.] (2,)


In [8]:
arr3=np.full((2,3),100)
print(arr3,arr3.shape)

[[100 100 100]
 [100 100 100]] (2, 3)


In [9]:
arr4=np.eye(3)
print(arr4,arr4.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [11]:
arr5=np.arange(1,10,2)
print(arr5,arr5.shape)

[1 3 5 7 9] (5,)


In [13]:
arr6=np.linspace(1,100,4)
print(arr6,arr6.shape)

[  1.  34.  67. 100.] (4,)
