In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshape_arr=arr.reshape((3,2))
print(reshape_arr,reshape_arr.shape)
flattend=arr.flatten()
print(flattend,flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
