In [1]:
import numpy as np

In [2]:
#indexing in 1-D array
arr=np.array([1,2,3])
print(arr[0])

1


In [3]:
#indexing in 2-D array
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[0,0])

1


In [8]:
#fancy indexing
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
    [100, 110, 120]
])

print(arr2[[0,2]])
print(arr2[:, [0, 2]])
print(arr2[[0, 2, 3], [1, 2, 0]])

[[10 20 30]
 [70 80 90]]
[[ 10  30]
 [ 40  60]
 [ 70  90]
 [100 120]]
[ 20  90 100]


In [11]:
#boolean indexing
arr4=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(arr4[arr4%2==0])
print(arr4[arr4>3])

[ 2  4  6  8 10 12 14]
[ 4  5  6  7  8  9 10 11 12 13 14]
