In [1]:
import numpy as np

In [3]:
#copy vs viwe
list=[1,2,3,4,5,6,7,8]
sub_list=list[1:4]
print(list)
print(sub_list)
sub_list[0]=100
print(sub_list)
print(list)


np_list=np.array([1,2,3,4,5,6,7,8])
np_sub=np_list[1:4] #if .copy() method is used then the changes will not refeclt at original array
print(np_list)
print(np_sub)
np_sub[0]=100
print(np_sub)
print(np_list)

[1, 2, 3, 4, 5, 6, 7, 8]
[2, 3, 4]
[100, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]
[2 3 4]
[100   3   4]
[  1 100   3   4   5   6   7   8]
