In [1]:
import numpy as np

In [2]:
#3-D array
arr3D=np.array([
    [[1,2],[3,4]],[[5,6],[7,8]]
])
print(arr3D,arr3D.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


In [7]:
#Indexing
print(arr3D[0,1,1])
print(arr3D[:,0,:])
print(arr3D[:,:,1])

4
[[1 2]
 [5 6]]
[[2 4]
 [6 8]]
