In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
print(arr1*3) #vectorization

[ 3  6  9 12 15]


In [3]:
#boradcasting
arr2=np.array([1,2,3,4,5,6])
arr3=np.array([2])
print(arr2+arr3)

arr4=np.array([[1,2,3,4,5],[2,3,7,8,9],[6,4,3,2,5]]) #ValueError
arr5=np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
# print(arr4+arr5)

[3 4 5 6 7 8]


In [4]:
# ============================================================
# NUMPY BROADCASTING
# ============================================================

# 1. What is Broadcasting?
# ------------------------
# Broadcasting is a NumPy feature that allows arithmetic operations
# between arrays of different shapes, provided their shapes are compatible.
#
# NumPy automatically adjusts how the arrays are compared during the operation.
# It does not necessarily create a new, permanently resized array.


# 2. Rules of Broadcasting
# ------------------------
# Rule 1: Compare the shapes from RIGHT to LEFT.
#
# Rule 2: Two dimensions are compatible if:
#         - They are equal, OR
#         - One of them is 1.
#
# Rule 3: If one shape has fewer dimensions, assume 1s are added
#         to its LEFT side.
#
# Rule 4: If any pair of dimensions is incompatible, NumPy raises
#         a ValueError.


# 3. Example: Broadcasting a 1D Array with a 2D Array
# ---------------------------------------------------

# import numpy as np
#
# arr1 = np.array([[1, 2, 3],
#                  [4, 5, 6]])
#
# arr2 = np.array([10, 20, 30])
#
# print(arr1.shape)  # (2, 3)
# print(arr2.shape)  # (3,)
#
# Broadcasting comparison:
#
# arr1 shape: (2, 3)
# arr2 shape:    (3,)
#
# Add an imaginary leading dimension of 1 to arr2:
#
# arr1 shape: (2, 3)
# arr2 shape: (1, 3)
#
# Compare dimensions from right to left:
#
# 3 == 3  -> Compatible
# 2 vs 1  -> Compatible because one dimension is 1
#
# Therefore, broadcasting is possible.
#
# print(arr1 + arr2)
#
# Output:
# [[11 22 33]
#  [14 25 36]]
#
# Explanation:
# NumPy adds [10, 20, 30] to each row of arr1.


# 4. Example: Broadcasting Two Incompatible Arrays
# ------------------------------------------------

# arr1 = np.array([1, 2, 3])
# arr2 = np.array([10, 20])
#
# print(arr1.shape)  # (3,)
# print(arr2.shape)  # (2,)
#
# Broadcasting comparison:
#
# arr1 shape: (3,)
# arr2 shape: (2,)
#
# Compare the dimensions:
#
# 3 vs 2 -> Incompatible
#
# Neither dimension is equal to the other, and neither is 1.
# Therefore, broadcasting is not possible.
#
# print(arr1 + arr2)
#
# Expected result:
# ValueError: operands could not be broadcast together
#
# Note: The error message may include the two incompatible shapes.


# 5. Broadcasting Shape Examples
# ------------------------------
#
# (3,) and (3,)       -> Compatible
# (3,) and (1,)       -> Compatible
# (3,) and (2, 3)     -> Compatible
# (1, 3) and (2, 3)   -> Compatible
# (2, 1) and (1, 3)   -> Compatible; result shape is (2, 3)
# (3,) and (2,)       -> Incompatible
# (2, 3) and (2, 2)   -> Incompatible
#
# Remember:
# Dimensions must be equal or one of them must be 1.


# 6. Broadcasting vs. Array Creation Errors
# -----------------------------------------
#
# These are TWO DIFFERENT situations.
#
# A. Broadcasting error:
#
# The arrays are created successfully, but their shapes are incompatible
# for the requested operation.
#
# Example:
#
# arr1 = np.array([1, 2, 3])  # Shape: (3,)
# arr2 = np.array([10, 20])   # Shape: (2,)
# result = arr1 + arr2        # Broadcasting error
#
#
# B. Array creation error:
#
# NumPy cannot create a regular multidimensional array because the
# nested lists have different lengths.
#
# Example:
#
# arr = np.array([[1, 2, 3, 4, 5],
#                 [2, 3]])
#
# The first row contains 5 elements.
# The second row contains 2 elements.
#
# NumPy generally raises a ValueError when creating a regular array
# from these unequal-length rows.
#
# The error occurs at np.array(...), before any addition is attempted.


# 7. Quick Revision
# -----------------
#
# 1. Broadcasting allows operations between compatible array shapes.
# 2. Compare dimensions from right to left.
# 3. Dimensions must be equal or one of them must be 1.
# 4. Missing dimensions are treated as 1 on the left.
# 5. Unequal nested-list lengths can cause an array creation error.
# 6. An array creation error is different from a broadcasting error.
# ============================================================